- hosts: loadbalancers
  become: true
  tasks:
    # Firewall tasks
    - name: "Firewall: Allow OpenSSH"
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: "Firewall: Allow http"
      community.general.ufw:
        rule: allow
        port: http

    - name: "Firewall: Allow https"
      community.general.ufw:
        rule: allow
        port: https

    - name: "Firewall: Enable"
      community.general.ufw:
        default: deny
        state: enabled
    # End Firewall tasks

    - name: Install certificates
      ansible.builtin.copy:
        src: exerge.pem
        dest: /etc/ssl/exerge.pem
        mode: '0600'

    - name: Install HAProxy # HAProxy
      ansible.builtin.apt:
        name: haproxy

    - name: Configure HAProxy
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify:
        - Restart HAProxy

  handlers:
    - name: Restart HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted


- hosts: dbservers
  become: true
  tasks:
    # Firewall tasks
    - name: "Firewall: Allow OpenSSH"
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: "Firewall: Allow http from loadbalancers"
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        port: '{{ http_port }}'
      loop:
        - '{{ groups['loadbalancers'] }}'

    - name: "Firewall: Allow http from webservers"
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        port: '{{ http_port }}'
      loop:
        - '{{ groups['webservers'] }}'

    - name: "Firewall: Allow nfs"
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        port: nfs
      loop:
        - '{{ groups['webservers'] }}'

    - name: "Firewall: Enable"
      community.general.ufw:
        default: deny
        state: enabled
    # End Firewall tasks

    - name: Install Python 3 pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install PyMongo
      ansible.builtin.pip:
        name: pymongo
        state: present

    - name: Install MongoDB package signing key # MongoDB
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present

    - name: Install MongoDB repository
      ansible.builtin.apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_lsb.codename }}/mongodb-org/5.0 multiverse
        state: present
        filename: mongodb-org-5.0

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present
        update_cache: true

    - name: Configure MongoDB
      ansible.builtin.template:
        src: mongod.conf.j2
        dest: /etc/mongod.conf
        mode: '0644'

    - name: Start MongoDB
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        daemon_reload: true

    - name: Create admin user # User setup
      community.mongodb.mongodb_user:
        db: admin
        name: admin
        pass: "{{ mongodb_admin_password }}"
        state: present
        roles: root

    - name: Create user
      community.mongodb.mongodb_user:
        login_user: admin
        login_password: "{{ mongodb_admin_password }}"
        database: "{{ mongodb_database }}"
        name: "{{ mongodb_user }}"
        pass: "{{ mongodb_password }}"
        roles:
          - db: "admin"
            role: "readWrite"
          - db: "{{ mongodb_database }}"
            role: "readWrite"

    - name: Install NodeSource package signing key # Node
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Install NodeSource repository
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
        state: present
        filename: nodesource

    - name: Install NodeSource-src repository
      ansible.builtin.apt_repository:
        repo: deb-src https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
        state: present
        filename: nodesource-src

    - name: Install Node.js (urK)
      ansible.builtin.apt:
        name: nodejs
        update_cache: true

    - name: Enable corepack
      ansible.builtin.command:
        cmd: "corepack enable"
      changed_when: false

    - name: Install Redis # Redis
      ansible.builtin.apt:
        name: redis-server

    - name: Configure Redis
      ansible.builtin.template:
        src: redis.conf.j2
        dest: /etc/redis/redis.conf
        mode: '0644'

    - name: Restart Redis
      ansible.builtin.service:
        name: redis
        state: restarted

    - name: Create nfs directory
      ansible.builtin.file:
        state: directory
        path: /nfs
        mode: '0644'

    - name: Create uploads directory
      ansible.builtin.file:
        state: directory
        path: "{{ uploads_dir }}"
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Install nfs server
      ansible.builtin.apt:
        name: nfs-kernel-server

    - name: Configure nfs exports
      ansible.builtin.template:
        src: nfs_exports.j2
        dest: "/etc/exports"
        mode: '0644'

    - name: Restart nfs
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted

    - name: Download simulator # Project
      become: false
      ansible.builtin.git:
        repo: https://github.com/chrfin-4/M7011E.git
        dest: /home/ubuntu/exerge
        depth: 1
        force: true
      register: simulator_repo

    - name: Deploy environment file
      ansible.builtin.template:
        src: envs_simulator.j2
        dest: "{{ repo_dest }}/simulator/.env"
        mode: '0644'
      become: false
      register: simulator_env

    - name: Yarn install
      ansible.builtin.command:
        chdir: "{{ repo_dest }}/simulator"
        cmd: "yarn install"
      become: false
      register: yarn_install
      changed_when: yarn_install.rc == 0

    - name: Install simulator in systemd
      ansible.builtin.template:
        src: simulator.service.j2
        dest: /etc/systemd/system/exerge_sim.service
        mode: '0644'

    - name: Start server
      ansible.builtin.systemd:
        state: restarted
        name: exerge_sim
        daemon_reload: true

  handlers:
    - name: Restart Redis
      ansible.builtin.service:
        name: redis
        state: restarted


- hosts: webservers
  become: true
  tasks:
    # Firewall tasks
    - name: "Firewall: Allow OpenSSH"
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: "Firewall: Allow http"
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        port: http
      loop:
        - "{{ groups['loadbalancers'] }}"

    - name: "Firewall: Enable"
      community.general.ufw:
        default: deny
        state: enabled
    # End Firewall tasks

    - name: Install nginx # Nginx
      ansible.builtin.apt:
        name: nginx

    - name: Configure nginx
      ansible.builtin.template:
        src: nginx-site.cfg.j2
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify:
        - Restart Nginx

    - name: Install NodeSource package signing key # Node
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Install NodeSource repository
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
        state: present
        filename: nodesource

    - name: Install NodeSource-src repository
      ansible.builtin.apt_repository:
        repo: deb-src https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
        state: present
        filename: nodesource-src

    - name: Install Node.js (urK)
      ansible.builtin.apt:
        name: nodejs
        update_cache: true

    - name: Enable corepack
      ansible.builtin.command:
        cmd: "corepack enable"
      changed_when: false

    - name: Create nfs directory
      ansible.builtin.file:
        state: directory
        path: /nfs
        mode: '0644'

    - name: Create uploads directory
      ansible.builtin.file:
        state: directory
        path: "{{ uploads_dir }}"
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Install nfs client
      ansible.builtin.apt:
        name: nfs-common

    - name: Mount nfs uploads directory
      ansible.posix.mount:
        src: "{{ groups['dbservers'][0] }}:{{ uploads_dir }}"
        path: "{{ uploads_dir }}"
        opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
        state: mounted

    - name: Download application # Project
      become: false
      ansible.builtin.git:
        repo: https://github.com/chrfin-4/M7011E.git
        dest: /home/ubuntu/exerge
        depth: 1
        force: true

    - name: Deploy server environment file
      ansible.builtin.template:
        src: envs_server.j2
        dest: "{{ repo_dest }}/server/.env"
        mode: '0644'
      become: false
      register: server_env

    - name: Deploy web environment file
      ansible.builtin.template:
        src: envs_web.j2
        dest: "{{ repo_dest }}/web/.env.local"
        mode: '0644'
      become: false
      register: web_env

    - name: Yarn install server
      ansible.builtin.command:
        chdir: "{{ repo_dest }}/server"
        cmd: "yarn install"
      become: false
      register: yarn_install
      changed_when: yarn_install.rc == 0

    - name: Yarn install web
      ansible.builtin.command:
        chdir: "{{ repo_dest }}/web"
        cmd: "yarn install"
      become: false
      register: yarn_install
      changed_when: yarn_install.rc == 0

    - name: Build frontend
      become: false
      ansible.builtin.command:
        chdir: "{{ repo_dest }}/web"
        cmd: "yarn build"
      register: yarn_build
      changed_when: yarn_build.rc == 0

    - name: Install server in systemd
      ansible.builtin.template:
        src: server.service.j2
        dest: /etc/systemd/system/exerge.service
        mode: '0644'

    - name: Install webapp in systemd
      ansible.builtin.template:
        src: webapp.service.j2
        dest: /etc/systemd/system/exerge_web.service
        mode: '0644'

    - name: Start server
      ansible.builtin.systemd:
        state: restarted
        name: exerge
        daemon_reload: true

    - name: Start webapp
      ansible.builtin.systemd:
        state: restarted
        name: exerge_web
        daemon_reload: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
